spring:
  application:
    name: social-media

  datasource:
    url: jdbc:mysql://localhost:3306/social-media?sslMode=DISABLED
    username: root
    password: mySecr3t46
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  http:
    multipart:
      max-file-size: 20MB


logging:
  level:
    org.hibernate: debug

management:
  security:
    enabled: false

server:
  port: 8084

info:
  app:
    name: Practice SpringBoot
    provider: Sammy
  contact:
    website: www.nesistec.co.uk/aboutUs